# Generated by Django 3.2 on 2021-05-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20210521_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість на складі'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_out',
            field=models.PositiveIntegerField(default=0, verbose_name='Продано'),
        ),
    ]
