# Generated by Django 3.2 on 2021-05-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_remove_product_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ua',
            field=models.CharField(max_length=255, null=True, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ua',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='spec',
            name='key_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spec',
            name='key_ua',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spec',
            name='value_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spec',
            name='value_ua',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
