# Generated by Django 3.2 on 2021-05-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20210530_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_ru',
            new_name='name_ua',
        ),
        migrations.RenameField(
            model_name='spec',
            old_name='key_ru',
            new_name='key_ua',
        ),
        migrations.RenameField(
            model_name='spec',
            old_name='value_ru',
            new_name='value_ua',
        ),
    ]
