# Generated by Django 3.2 on 2021-05-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_auto_20210531_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='key_en',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='key_uk',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='value_en',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='value_uk',
        ),
    ]
