# Generated by Django 3.2 on 2021-05-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_auto_20210531_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='value_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spec',
            name='value_uk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
