# Generated by Django 3.2 on 2021-05-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_auto_20210531_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='key_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spec',
            name='key_uk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
