# Generated by Django 3.2 on 2021-05-31 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_auto_20210531_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug_uk',
        ),
    ]
