# Generated by Django 3.2 on 2021-06-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20210531_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
