# Generated by Django 3.2 on 2021-06-09 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='product.product'),
        ),
    ]
