# Generated by Django 3.2 on 2021-06-23 16:45

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_alter_product_category'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Категорії'),
        ),
    ]
