# Generated by Django 3.2 on 2021-06-23 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0068_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 23, 16, 39, 31, 451811, tzinfo=utc), verbose_name='Дата на виконання'),
        ),
    ]
