# Generated by Django 3.2 on 2021-07-23 07:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0073_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 23, 7, 44, 11, 275172, tzinfo=utc), verbose_name='Дата на виконання'),
        ),
    ]
